version: '3.8'

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./ansible:/opt/ansible
    networks:
      - jenkins-net
    restart: unless-stopped

volumes:
  jenkins_home:
    driver: local

networks:
  jenkins-net:
    driver: bridge
